#!/usr/local/bin/perl

use lib 'lib';

use 5.010;
use warnings;
use strict;
use Protojail::Application;

#-------------------------------------------------------------------------------
#  Check for root privs.
#-------------------------------------------------------------------------------
my $name = `whoami`; 
 
die "root priviledges required!\n" if $name ne "root";

my $app = Protojail::Application->new();
$app->run();
